### ISSUE TITLE
You love To See it 

### ISSUE THREAD

**Issue by tr1xongithub** [Knakiri/sleak-crypter-leaked#1]
Everyone come admire this leak . Man gets mad of his wrong doing and puts old source code on github 🤣🤣🤣🤣 as if it was gonna do somthing lol

**Comment by Knakiri** [comment]
you were also wrong

**Comment by Knakiri** [comment]
> Everyone come admire this leak . Man gets mad of his wrong doing and puts old source code on github 🤣🤣🤣🤣 as if it was gonna do somthing lol

thats why you were so scared deleted all the links involved with the crypter and i carried you so hard lol
